---
baseURL: "https://schemahero.io"
languageCode: "en-us"
title: "SchemaHero - A modern approach to database schema migrations"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation for SchemaHero."
googleAnalytics: ""

# Algolia search
algolia:
  index: "prod_schemahero"
  appID: "QVPBAZBRCD"

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
  - ./static

Params:
  author: "SchemaHero"
  copyright: "Replicated, Inc"
  homepage_intro: "Kubernetes-Native, Declarative Database Schema Management"

  schemaheroVersion: 0.8.1
  schemaheroAPIVersion: v1alpha3

  favicon: ""
  pagetitle: "SchemaHero"
  permalink: "#"
  mainSections:
    - overview
    - cli
    - docs
    - databases
    - tutorial
    - reference
menu:
  main:
    - Identifier: "tutorial"
      Name: "Tutorial"
      Weight: 1
      URL: "/tutorial"
    - Identifier: "docs"
      Name: "Documentation"
      Weight: 2
      URL: "/docs/concepts/about/"
    - Identifier: "databases"
      Name: "Databases"
      Weight: 3
      URL: "/databases/postgres/"
    - Identifier: "cli"
      Name: "CLI"
      weight: 4
      URL: "/cli/install/"
    - Identifier: "community"
      Name: "Community"
      Weight: 5
      URL: "/community"
---
