---
baseURL: "https://schemahero.io"
languageCode: "en-us"
title: "schemahero.io"
theme: "hugo-whisper-theme"
metadataformat: "yaml"
canonifyurls: true
description: "Documentation for SchemaHero."
googleAnalytics: ""

# Algolia search
algolia:
  index: "prod_schemahero"
  appID: "QVPBAZBRCD"

# Hugo configuration
pygmentsCodeFences: true
pygmentsStyle: "monokai"

staticDir:
    - ./static

Params:
  author: "SchemaHero"
  copyright: "Replicated, Inc"
  homepage_intro: "Kubernetes-Native, Declarative Database Schema Management"

  favicon: ""
  pagetitle: "SchemaHero"
  permalink: "#"
  mainSections:
    - overview
    - cli
    - docs
    - databases
    - tutorial
menu:
  main:
    - Name: "Overview"
      Weight: 1
      URL: "/overview"
    - Name: "CLI"
      weight: 2
      URL: "/cli"
    - Name: "Documentation"
      Weight: 3
      URL: "/docs"
    - Name: "Databases"
      Weight: 4
      URL: "/databases"
    - Name: "Tutorial"
      Weight: 5
      URL: "/tutorial"
---
